//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailSender
{
    using System;
    using System.Collections.Generic;
    
    public partial class mails
    {
        public long id { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Attachment { get; set; }
        public long sender_id { get; set; }
        public long reciever_id { get; set; }
        public string sended { get; set; }
    
        public virtual recievers recievers { get; set; }
        public virtual senders senders { get; set; }
    }
}
